name: CI

on:
  push:
    branches:
      - '1.0.0'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}_${{ env.cache-name }}_${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}_${{ env.cache-name }}_

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint

  check-type:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}_${{ env.cache-name }}_${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}_${{ env.cache-name }}_

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Check type
        run: yarn type-check

  build:
    needs: [lint, check-type]
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    env:
      cache-dir: 'dist/views/cache'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        env:
          CI: true
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}_${{ env.cache-name }}_${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}_${{ env.cache-name }}_

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache node build artifact
        uses: actions/cache@v2
        id: cache-build-artifact
        env:
          cache-name: cache-build-artifact
        with:
          path: '**/dist'
          key: ${{ runner.os }}_${{ env.cache-name }}_${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}_${{ env.cache-name }}_

      - name: Build
        env:
          NODE_ENV: production
        run: |
          npx next telemetry disable
          yarn build